m: 50
D: 8
iters: 60000
batch: 1024
lr: 5e-3  # 安定した学習率
sigma_z: 0.05
ode_steps: 25
seed: 42
device: "auto"     # "cuda"|"cpu"|"mps"|"auto"
out_dir: "checkpoints"
use_scheduler: false
warmup_ratio: 0.05
weight_decay: 0.0
trace_penalty: 0.0
lambda_j: 0.0
lambda_k: 0.0
lambda_tr: 0.0
grad_clip: 1.0
ckpt_every: 5000
log_every: 200
probe: 0
cpu: false
