$latex    = 'uplatex -synctex=1 -halt-on-error -interaction=nonstopmode %O %S';
$bibtex   = 'biber %O %B';
$dvipdf   = 'dvipdfmx %O -o %D %S';
$pdf_mode = 3;      # dvi -> pdf
$aux_dir  = 'build';
$out_dir  = 'build';
